[package]
name = "bloom"
version = "0.1.0"
authors = ["Maxim Molchanov <m.molchanov@vonmo.com>"]
license = "MIT/Apache-2.0"

[lib]
name = "bloom"
crate-type = ["dylib"]

[dependencies]
rustler = ">=0.13.0"
bloomfilter = "1"
